Repository vmware/powershell-module-for-vmware-cloud-foundation-power-management, pull requests merged in 2023-06, with the labels that each got.

#22 chore(gha): pin actions to commit sha
  .github/workflows/issues.yml
  .github/workflows/lock-threads.yml
  .github/workflows/pull-requests.yml
  .github/workflows/stale.yml
Labels: chore, github-actions

#25 chore: project updates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  NOTICE
  VMware.CloudFoundation.PowerManagement.psd1
Labels: documentation, chore, needs-review

#26 ci(module): add basic module ci
  .ci/pester-tests.ps1
  .github/workflows/ci-module.yml
Labels: chore, github-actions, needs-review

#27 chore: update each cmdlet to include the `.PARAMETER` details
  CHANGELOG.md
  VMware.CloudFoundation.PowerManagement.psd1
  VMware.CloudFoundation.PowerManagement.psm1
Labels: chore

#28 docs: add cmdlet documentation
  docs/documenatation/functions/Get-DrsAutomationLevel.md
  docs/documenatation/functions/Get-EdgeNodeFromNSXManager.md
  docs/documenatation/functions/Get-MaintenanceMode.md
  docs/documenatation/functions/Get-NSXTComputeManagers.md
  docs/documenatation/functions/Get-SSHEnabledStatus.md
  docs/documenatation/functions/Get-TanzuEnabledClusterStatus.md
  docs/documenatation/functions/Get-VMRunningStatus.md
  docs/documenatation/functions/Get-VMToClusterMapping.md
  docs/documenatation/functions/Get-VMsWithPowerStatus.md
  docs/documenatation/functions/Get-VamiServiceStatus.md
  docs/documenatation/functions/Get-poweronVMsOnRemoteDS.md
  docs/documenatation/functions/Invoke-EsxCommand.md
  docs/documenatation/functions/Set-DrsAutomationLevel.md
  docs/documenatation/functions/Set-MaintenanceMode.md
  docs/documenatation/functions/Set-Retreatmode.md
  docs/documenatation/functions/Set-VamiServiceStatus.md
  docs/documenatation/functions/Set-VsanClusterPowerStatus.md
  docs/documenatation/functions/Set-VsphereHA.md
  docs/documenatation/functions/Start-CloudComponent.md
  docs/documenatation/functions/Stop-CloudComponent.md
  docs/documenatation/functions/Test-LockdownMode.md
  docs/documenatation/functions/Test-VsanHealth.md
  docs/documenatation/functions/Test-VsanObjectResync.md
  docs/documenatation/functions/Wait-ForStableNsxtClusterStatus.md
Labels: documentation, needs-review

#30 docs: add maintainers and collaborators
  docs/community/index.md
  mkdocs.yml
Labels: documentation, needs-review

#31 docs: update supported versions
  docs/index.md
Labels: documentation, needs-review

#32 chore(gh): fix bug issue form
  .github/ISSUE_TEMPLATE/bug.yml
Labels: chore, needs-review

#33 chore(gh): update issues config
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore, needs-review
