Repository vmware/powershell-module-for-vmware-cloud-foundation-power-management, pull requests merged in 2023-11, with the labels that each got.

#69 docs: add air-gapped install
  docs/documentation/getting-started/install.md
  docs/snippets/copy-module-local-linux.sh
  docs/snippets/copy-module-local-windows.ps1
  docs/snippets/import-module-local-linux.ps1
  docs/snippets/pre-req-linux.sh
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation

#73 feat: add secure strings for sensitive parameters
  CHANGELOG.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  SampleScripts/PowerManagement-WorkloadDomain.ps1
  VMware.CloudFoundation.PowerManagement.psd1
  VMware.CloudFoundation.PowerManagement.psm1
Labels: enhancement

#75 feat: add support for vxrail cluster shutdown API
  CHANGELOG.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  SampleScripts/PowerManagement-WorkloadDomain.ps1
  VMware.CloudFoundation.PowerManagement.psm1
  docs/documentation/functions/Invoke-VxrailClusterShutdown.md
  docs/index.md
Labels: enhancement

#78 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  README.md
  VMware.CloudFoundation.PowerManagement.psd1
  VMware.CloudFoundation.PowerManagement.psm1
  docs/index.md
  mkdocs.yml
Labels: chore
