Repository vmware/powershell-module-for-vmware-cloud-foundation-power-management, pull requests merged in 2023-07, with the labels that each got.

#37 feat: add support for vcf 5.0
  CHANGELOG.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  SampleScripts/PowerManagement-WorkloadDomain.ps1
Labels: documentation

#38 chore: update `RequiredModules`
  CHANGELOG.md
  VMware.CloudFoundation.PowerManagement.psd1
  docs/snippets/install-module.ps1
Labels: documentation, dependencies, needs-review

#47 chore(gh): add to project
  .github/workflows/project.yml
Labels: chore, github-actions
