Repository vmware/powershell-module-for-vmware-cloud-foundation-power-management, pull requests merged in 2024-01, with the labels that each got.

#83 docs: update for connected and disconnected
  docs/documentation/getting-started/install.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#85 refactor: replace use of `Test-NetConnection`
  CHANGELOG.md
  LICENSE
  Makefile
  NOTICE
  README.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  SampleScripts/PowerManagement-WorkloadDomain.ps1
  VMware.CloudFoundation.PowerManagement.psd1
  VMware.CloudFoundation.PowerManagement.psm1
  docs/requirements.txt
  docs/snippets/import-module-local-linux.ps1
  docs/snippets/import-module.ps1
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
  docs/snippets/update-modules.ps1
  mkdocs.yml
Labels: documentation, needs-review

#86 refactor: modify if statement for `nsxtedgeNodes`
  CHANGELOG.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  VMware.CloudFoundation.PowerManagement.psd1
Labels: documentation, needs-review

#87 feat: add support for aria operations for logs shutdown
  CHANGELOG.md
  SampleScripts/PowerManagement-ManagementDomain.ps1
  VMware.CloudFoundation.PowerManagement.psd1
Labels: documentation, enhancement, needs-review
