Repository vmware/powershell-module-for-vmware-cloud-foundation-power-management, pull requests merged in 2025-05, with the labels that each got.

#119 docs: sanitize examples
  docs/documentation/functions/Get-DrsAutomationLevel.md
  docs/documentation/functions/Get-EdgeNodeFromNSXManager.md
  docs/documentation/functions/Get-MaintenanceMode.md
  docs/documentation/functions/Get-NSXTComputeManagers.md
  docs/documentation/functions/Get-poweronVMsOnRemoteDS.md
Labels: documentation

#127 docs: update docs
  docs/community/index.md
  docs/community/support.md
  docs/index.md
  docs/snippets/install-module.ps1
  docs/snippets/vars-vcf.ps1
Labels: documentation

#122 chore: update coc
  CODE_OF_CONDUCT.md
Labels: documentation, chore, needs-review

#121 chore(gh): update workflows
  .github/workflows/docs.yml
  .github/workflows/issues.yml
  .github/workflows/lock.yml
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/tests.yml
  .gitignore
Labels: chore, github-actions, needs-review

#124 chore: update license
  LICENSE
  NOTICE
Labels: chore, needs-review

#125 chore: update readme
  README.md
Labels: documentation, chore, needs-review
